
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 06 16:55:05 CST 2023
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PuntoComa = 31;
  public static final int InicioDoWhile = 27;
  public static final int InicioWhile = 25;
  public static final int CadenaDeTexto = 34;
  public static final int Comentario = 18;
  public static final int MayorIgualQue = 23;
  public static final int Else = 16;
  public static final int TipoEntero = 5;
  public static final int NoNumero = 35;
  public static final int FinIf = 15;
  public static final int InicioFor = 29;
  public static final int Division = 13;
  public static final int AbreParentesis = 32;
  public static final int InicioIf = 14;
  public static final int FinElse = 17;
  public static final int EOF = 0;
  public static final int IgualQue = 21;
  public static final int MayorQue = 19;
  public static final int error = 1;
  public static final int SignoIgual = 9;
  public static final int MenorIgualQue = 24;
  public static final int Linea = 2;
  public static final int RTrue = 39;
  public static final int ERROR = 38;
  public static final int TipoCadena = 7;
  public static final int DiferenteQue = 22;
  public static final int CierraParentesis = 33;
  public static final int FinDoWhile = 28;
  public static final int TipoDecimal = 6;
  public static final int Identificador = 37;
  public static final int Resta = 11;
  public static final int MenorQue = 20;
  public static final int FinPrograma = 4;
  public static final int InicioPrograma = 3;
  public static final int RFalse = 40;
  public static final int Multiplicacion = 12;
  public static final int NUMDECIMAL = 41;
  public static final int Numero = 36;
  public static final int FinWhile = 26;
  public static final int Suma = 10;
  public static final int TipoBooleano = 8;
  public static final int FinFor = 30;
}

